version: "3"
services:
  frontend:
    image: jobster-client
    restart: unless-stopped
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  backend:
    image: jobster-server
    restart: unless-stopped
    env_file:
      - /home/.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - "5000:5000"
    networks:
      - mern-app
  nginx: 
    image: nginx:latest
    restart: unless-stopped
    ports: 
      - "${SSL_PORT}:443"
      - "${HTTP_PORT}:80"
      # this is where the nginx server is located
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local