version: '3.3'
services:
  nginx: 
  image: nginx:latest
  restart: unless-stopped
    ports: 
      - "${SSL_PORT}:443"
      - "${HTTP_PORT}:80"
      # this is where the nginx server is located
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem 
  mongodb:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - /home/.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - '5000:5000'

    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
