version: '3.3'
services:
  mongodb:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
